name: main
on:
  push:
    branches: ['__CI_BRANCH__']
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '__NODE_VERSION__'
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
      - run: yarn run typecheck
