name: main
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'
jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: cli
      - uses: actions/checkout@v2
        with:
          path: toolkit-project
          ref: toolkit-project
          token: ${{ secrets.ACCESS_TOKEN_WITH_WORKFLOW_PERMISSIONS }}

      - uses: actions/setup-node@v1
        with:
          node-version: '12.20.1'

      - name: Restore node_modules cache
        uses: actions/cache@v1
        with:
          path: ./cli/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('cli/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - run: yarn install
        working-directory: cli

      - run: yarn run test
        working-directory: cli

      - run: yarn run build && chmod +x cli.js
        working-directory: cli

      - run: npm pack
        working-directory: cli

      - name: Create project
        working-directory: toolkit-project
        run: |
          rm -f yarn.lock package.json .*.js *.js .*rc *.tgz
          rm -rf .github .vscode scripts src
          touch yarn.lock
          cp ../cli/*.tgz ./
          ../cli/cli.js \
              --dangerously-enable-ci-environment \
              --dangerously-set-github-ci-branch toolkit-project \
              --tailwind \
              --nextjs \
              --docker \
              --github-ci \
              --typescript \
              --vscode \
              --jest \
              --skip-install
          ls -al
          cat package.json
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git add --force *.tgz
          git status
          git diff --quiet && git diff --staged --quiet || \
            git commit -m "Generate project"

      - name: Push commit to generate new project
        if: github.ref == 'refs/heads/main'
        working-directory: toolkit-project
        run: git push -f origin toolkit-project
