name: main
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'
jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.20.1
      - uses: bahmutov/npm-install@v1
        env:
          NODE_ENV: production

      - name: Create project
        run: |
          mkdir cli-project
          cd cli-project
          ../cli.js --dry-run
          ls -al

          # cp -R create-react-project-app-01/.git new-project/.git
          # rm -rf create-react-project-app-01
          # mv new-project create-react-project-app-01
          # cd create-react-project-app-01
          # git config user.name github-actions
          # git config user.email github-actions@github.com
          # git add .
          # git diff --quiet && git diff --staged --quiet || \
          #   git commit -m "[gh-actions] Push new version of the project"
