name: main
on:
  push:
    branches: [main]
jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: toolkit-project
          ref: toolkit-project
          token: ${{ secrets.ACCESS_TOKEN_WITH_WORKFLOW_PERMISSIONS }}

      - uses: actions/setup-node@v1
        with:
          node-version: 12.20.1
      - uses: bahmutov/npm-install@v1
        env:
          NODE_ENV: production

      - name: Create project
        run: |
          cd toolkit-project
          cp ../.gitignore .gitignore
          rm -f yarn.lock package.json .*.js *.js .*rc
          rm -rf .github .vscode scripts src
          ../cli.js --ci
          ls -al
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || \
            git commit -m "Generate project" && git push -f origin toolkit-project
