name: main
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'
jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          path: toolkit-project
          ref: toolkit-project
          token: ${{ secrets.ACCESS_TOKEN_WITH_WORKFLOW_PERMISSIONS }}

      - uses: actions/setup-node@v1
        with:
          node-version: 12.20.1
      - uses: bahmutov/npm-install@v1
        env:
          NODE_ENV: production

      - run: npm pack
      - name: Create project
        run: |
          cd toolkit-project
          ../cli.js --dry-run
          ls -al
          git config user.name "Github Actions"
          git config user.email actions@github.com
          git add .
          git diff --quiet && git diff --staged --quiet || \
            git commit -m "[gh-actions] Push new version of the project"
          git push -f origin toolkit-project
